---
- name: Verify - config AWX with base settings
  hosts: all
  become: false
  tasks:
    - name: Check that if default page is running
      ansible.builtin.uri:
        url: "http://localhost{{ nginx__port_http }}"
        return_content: true
      register: local_webserver_output
      # failed_when: this is failed or "'AWESOME' not in this.content"

    - name: Show output
      debug:
        var: local_webserver_output
